FROM kathara/common:latest
LABEL org.opencontainers.image.authors="Network Security Group, ETH Zurich <netsec.ethz.ch>"

# Install SCION from GitHub release
ARG TARGETARCH
ARG VERSION

WORKDIR /tmp

RUN wget https://github.com/scionproto/scion/releases/download/v${VERSION}/scion_${VERSION}_deb_$TARGETARCH.tar.gz && \
	tar xfz scion_* && \
	apt install ./scion*.deb && \
	rm scion_* && \
	apt clean && \
	rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

# Strip templating from systemd service files, systemd-replacement-script does not support it
RUN mv /usr/lib/systemd/system/scion-router\@.service /usr/lib/systemd/system/scion-router.service && \
	sed -i 's/%i/br/g' /usr/lib/systemd/system/scion-router.service && \
	mv /usr/lib/systemd/system/scion-control\@.service /usr/lib/systemd/system/scion-control.service && \
	sed -i 's/%i/cs/g' /usr/lib/systemd/system/scion-control.service
