FROM kathara/common:latest
LABEL org.opencontainers.image.authors="Kathara Team <contact@kathara.org>"

ARG VERSION

RUN curl -s https://deb.frrouting.org/frr/keys.asc | apt-key add -   

RUN echo "deb https://deb.frrouting.org/frr $(lsb_release -s -c) \"frr-${VERSION}\"" | tee -a /etc/apt/sources.list.d/frr.list 

RUN apt update && \
	apt install -y --no-install-recommends \
	frr \
	frr-pythontools \
	frr-rpki-rtrlib && \
	apt clean && \
	rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

RUN sed -i -e 's/service/no service/' /etc/frr/vtysh.conf \
	&& rm /etc/frr/frr.conf

COPY su_frr.conf /etc/systemd/system/frr.service.d/su_frr.conf