# Stage to build latest iproute release
FROM debian:12 AS iproute

ARG DEBIAN_FRONTEND="noninteractive"
RUN apt update && \
	apt install -y --no-install-recommends \
	bison \
	build-essential \
	ca-certificates \
	flex \
	git \
	libbpf-dev \
	libcap-dev \
	libmnl-dev \
	pkg-config

WORKDIR /tmp

RUN	mkdir output && \
	git clone https://git.kernel.org/pub/scm/network/iproute2/iproute2.git && \
	cd iproute2 && \
	git checkout $(git describe --tags --abbrev=0) && \
	./configure && \
	make -j$(nproc) && \
	DESTDIR=/tmp/output make install

# Build the final image
FROM debian:12
LABEL org.opencontainers.image.authors="Kathara Team <contact@kathara.org>"

ENV LANG="C.UTF-8"
ENV LC_ALL="C.UTF-8"

COPY .bashrc /root/.bashrc

ARG DEBIAN_FRONTEND="noninteractive"
RUN apt update && \
	apt upgrade -y && \
	apt install --no-install-recommends -y \
	apt-utils \
	apt-transport-https \
	arping \
	bridge-utils \
	curl \
	diffutils \
	dnsutils \
	dublin-traceroute \
	ethtool \
	expect \
	git \
	gnupg \
	hping3 \
	iperf3 \
	iptables \
	iputils-ping \
	iputils-tracepath \
	less \
	libbpf1 \
	libelf1 \
	links \
	lsb-base \
	lsb-release \
	man-db \
	mtr-tiny \
	nano \
	ndisc6 \
	net-tools \
	netbase \
	netcat-openbsd \
	openssh-client \
	openssl \
	python3-pip \
	radvd \
	rsync \
	screen \
	sed \
	systemd-userdbd \
	tar \
	tcpdump \
	telnet \
	tmux \
	traceroute \
	wget && \
	apt clean && \
	rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

ADD https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py /usr/local/bin/systemctl

RUN	chmod +x /usr/local/bin/systemctl

COPY --from=iproute /tmp/output/sbin /sbin
COPY --from=iproute /tmp/output/usr /usr

RUN python3 -m pip install --no-cache-dir --upgrade --break-system-packages pip && \
	python3 -m pip install --no-cache-dir --break-system-packages scapy tabulate

WORKDIR /

VOLUME /hosthome
VOLUME /shared