FROM kathara/core:latest
LABEL org.opencontainers.image.authors="Kathara Team <contact@kathara.org>"

ARG TARGETARCH

RUN wget -qO - "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC4BF02689F87C61287782DCCC928FEB3B3E94585" | gpg --dearmor -o /usr/share/keyrings/bird-pkg.gpg && \
	echo "deb [signed-by=/usr/share/keyrings/bird-pkg.gpg] https://ppa.launchpadcontent.net/cz.nic-labs/bird/ubuntu jammy main" | tee /etc/apt/sources.list.d/bird.list

RUN apt update && \
	apt install -y --no-install-recommends \
	bird2=2.17.2-cznic.1~jammy golang-go && \
	apt clean && \
	rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

RUN git clone https://github.com/alice-lg/birdwatcher.git && \
    cd birdwatcher && \
    sed -i "s/birdwatcher-linux-amd64/birdwatcher-linux-$TARGETARCH/g" install/systemd/birdwatcher4.service && \
    sed -i "s/birdwatcher-linux-amd64/birdwatcher-linux-$TARGETARCH/g" install/systemd/birdwatcher6.service && \
    make dist ARCH=$TARGETARCH && \
    cp -r DIST/* / && cd / && rm -rf birdwatcher