FROM kathara/common:12
LABEL org.opencontainers.image.authors="Kathara Team <contact@kathara.org>"

ENV LANG="C.UTF-8"
ENV LC_ALL="C.UTF-8"

ARG DEBIAN_FRONTEND="noninteractive"
RUN apt update
RUN apt upgrade -y
RUN apt install -y \
    apache2 \
    apache2-bin \
    bind9 \
    bind9-utils

RUN ln -s /etc/init.d/named /etc/init.d/bind

RUN apt clean && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*
