FROM kathara/frr

# Install Docker and Kathara
ARG DEBIAN_FRONTEND="noninteractive"
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# TODO: Enable this
# RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 21805A48E6CBBA6B991ABE76646193862B759810 && \
# echo "deb http://ppa.launchpad.net/katharaframework/kathara/ubuntu bionic main" > /etc/apt/sources.list.d/kathara.list && \
# echo "deb-src http://ppa.launchpad.net/katharaframework/kathara/ubuntu bionic main" >> /etc/apt/sources.list.d/kathara.list && \
# apt update && \
# apt install -y docker-ce docker-ce-cli containerd.io kathara xterm tree && \
# apt clean && \
# rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

# TODO: Remove this
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
  apt update && \
  apt install -y docker-ce docker-ce-cli containerd.io

# TODO: REMOVE
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F23C5A6CF475977595C89F51BA6932366A755776 && \
  echo 'deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic main' > /etc/apt/sources.list.d/deadsnakes.list && \
  echo 'deb-src http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic main' >> /etc/apt/sources.list.d/deadsnakes.list && \
  apt update && \
  apt remove -y python3.7 && \
  apt -y upgrade && \
  apt -y autoremove && \
  apt install -y python3.9 \
		python3.9-dev \
		python3.9-venv \
		python3-pip \
		python3.9-distutils && \ 
    python3.9 -m pip install --upgrade pip && \
  apt clean && \
  rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

# Install the Kathara Network Plugin by brutally copying the files inside the container's filesystem
COPY plugin.tar.gz /var/lib/docker/plugins/plugin.tar.gz
RUN tar xfvz /var/lib/docker/plugins/plugin.tar.gz -C /var/lib/docker/plugins/ && rm /var/lib/docker/plugins/plugin.tar.gz

__IMAGE__

# Switch iptables to legacy (Docker works with this one)
RUN update-alternatives --set iptables /usr/sbin/iptables-legacy && \
  update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy 

# Create the /run/xtables.lock required by iptables and Kathara Network Plugin
RUN touch /run/xtables.lock

# Copy the docker launcher
ADD rundocker /usr/local/bin/rundocker
RUN chmod +x /usr/local/bin/rundocker 

# Copy a pre-built kathara.conf file
COPY kathara.conf /root/.config/kathara.conf
# Add a env variable to know that this is a DinD container
RUN echo "alias kathara=\"/venv/bin/python3.9 /kathara/src/kathara.py\"" >> ~/.bashrc

# TODO: REMOVE 
COPY kathara/ /kathara
RUN python3.9 -m venv /venv && \
  /venv/bin/pip3.9 install -r /kathara/src/requirements.txt

# Declare /var/lib/docker as a volume in order to detach it from the overlayfs
VOLUME /var/lib/docker
ENTRYPOINT ["rundocker"]
