#!/bin/bash

# Close extraneous file descriptors.
pushd /proc/self/fd >/dev/null
for FD in *
do
	case "$FD" in
	# Keep stdin/stdout/stderr
	[012])
		;;
	# Nuke everything else
	*)
		eval exec "$FD>&-"
		;;
	esac
done
popd >/dev/null

# Remove previous .pid and .sock files
rm -rf /var/run/docker.pid /var/run/docker.sock

# Start Docker and wait that it starts
dockerd &>/var/log/docker.log &
until docker info >/dev/null 2>&1
do
	sleep 1
done

# Run a shell after completing the boot
/bin/bash